# Generated by Django 2.2.5 on 2019-11-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limiteSaqueDiario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flagAtivo', models.BooleanField()),
                ('tipoConta', models.PositiveSmallIntegerField()),
                ('dataCriacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('dataNascimento', models.DateField()),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataTransacao', models.DateTimeField()),
                ('simbolo_moeda', models.CharField(max_length=3)),
                ('idConta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='api.Conta')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='api.Pessoa'),
        ),
    ]
